version: '3.8'

services:
  storeui:
    image: shindouhiro/storeserver:latest
    container_name: storeui
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=http://api.example.com  # 生产环境API地址
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app_network

networks:
  app_network:
    external: true
