version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: nest-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_demo
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: nest_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nest:
    image: your-nest-image:latest      # 先用 docker build -t your-nest-image:latest . 构建好镜像
    container_name: nest-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=nest_user
      - DB_PASSWORD=nest_pass
      - DB_DATABASE=nest_demo
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
